- gril/grilrequest.c
- plugins/mtk.c
- unit/test-mtkrequest.c
A couple of fixes needed for arale
> SIM_MODE and session ID fixes for arale

- drivers/mtkmodem/voicecall.c
- drivers/rilmodem/rilutil.h
- drivers/rilmodem/voicecall.c
- drivers/rilmodem/voicecall.h
- plugins/mtk.c
- plugins/ril.c
Auto-answer calls for factory tests. See LP bug #1408555 for more information.
> Auto-answer calls when test SIM is present

- plugins/mtk.c
Single slot devices may not have RIL_REQUEST_RADIO_POWERON/OFF, use generic RIL_REQUEST_RADIO_POWER instead.
> mtkmodem: use RIL_REQUEST_RADIO_POWER for 1 slot

- plugins/mtk.c
In some cases RIL requests were failing because the radio was not actually on, even although the request for powering on the radio had been successful. It turns out that waiting for the request response is not enough and we need to wait for the radio event to confirm that the radio is really in the desired state.
This fixed LP bug: https://bugs.launchpad.net/ubuntu/+source/ofono/+bug/1419675
> Wait for radio event before onlining

- plugins/mtk.c
Setting flight mode was failing when the 3G slot was the second one and there was no SIM in the first slot. The reason was that the radio state reported for the first slot was always SIM_LOCKED_OR_ABSENT.
This PR fixes https://bugs.launchpad.net/ubuntu/+source/ofono/+bug/1430700
> mtk: Fix FM when the second slot is 3G

- plugins/ubuntu-apndb.c
- src/common.c
- unit/test-common.c
Provision initial LTE attach APNs from Android database.
> Provision IA APNs

- gril/grilunsol.c
We calculate the LTE signal strength in a similar way to what AOSP does (it was not really working before). Fixes bug #1433867.
> gril: Fix calculation of LTE signal strength

- drivers/mtkmodem/mtkrequest.h
- drivers/mtkmodem/mtkunsol.c
- drivers/mtkmodem/mtkunsol.h
- plugins/bluetooth.c
- plugins/mtk.c
- unit/test-mtkunsol.c
Switch modem FW for CMCC users depending on detected country. This implements LP bug #1427544
> Switch modem FW depending on SIM type and roaming conditions

- drivers/rilmodem/voicecall.c
Drop calls if we receive a radio not available error when polling the current list of voice calls.
Fix for https://bugs.launchpad.net/canonical-devices-system-image/+bug/1445580
> rilmodem: Drop calls if radio is not available

- src/gprs.c
Sync reset contexts implementation with ofono upstream.
> gprs: Sync reset contexts with upstream

- gril/gril.c
Remove traces that could be useful only for debugging problems in gril sending/receiving logic. This is currently well tested and the traces are very noisy.
> gril: Remove useless traces

- src/gprs.c
Set an LTE IA APN to preferred when we use it, or use the preferred one if the property was already set for one of the IA APNs.
This is part of the changes for the 'Preferred' bug:
https://bugs.launchpad.net/ubuntu-rtm/+source/ubuntu-system-settings/+bug/1361864
> gprs: Set preferred for the used IA APN

- test/list-contexts
Fix list-contexts after changes to support DNS lookups for MMS
> test: Fix printing context properties

- plugins/ril.c
Fix for LP #1490991. Exit instead of assert to avoid generating crash files.
> Do not assert when the radio is unavailable

- drivers/rilmodem/gprs-context.c
Fix crash that happened when retrying to close a context while the gprs-context atom had already been destroyed (LP: #1492483).
> Fix crash when retrying closing context

- gril/gril.c
Entries to the table of notification callbacks can be added by the callbacks while being called. This caused a glib error as gril was using an interator to the hash table while the table was being modified. Fixed by avoiding the unnecessary loop.
The error was seen in a bq 4.5 with 2 inserted SIMs while executing ofono from the command line:
(ofonod:10736): GLib-CRITICAL **: g_hash_table_iter_next: assertion 'ri->version == ri->hash_table->version' failed
> gril: Fix access to notify callbacks

- examples/emulator.c
- include/emulator.h
- plugins/dun_gw_bluez4.c
- plugins/dun_gw_bluez5.c
- plugins/hfp_ag_bluez4.c
- plugins/hfp_ag_bluez5.c
- plugins/phonesim.c
- plugins/upower.c
- src/emulator.c
- src/modem.c
- src/network.c
- src/ofono.h
- src/sim.c
- src/voicecall.c
> Support handling incoming calls for HFP + multi-SIM

- .gitignore
- Makefile.am
- drivers/rilmodem/call-barring.c
- gril/grilreply.c
- unit/test-rilmodem-cb.c
Add new call-barring unit tests.
These commits have already been accepted upstream.
> Add test rilmodem cb

- plugins/android-wakelock.c
- src/voicecall.c
- src/wakelock.c
Fix style issues found in the recently merged wakelock pull-request:
https://github.com/rilmodem/ofono/pull/227
> Fix wakelock style

- unit/rilmodem-test-server.c
- unit/rilmodem-test-server.h
- unit/test-rilmodem-cb.c
- unit/test-rilmodem-cs.c
- unit/test-rilmodem-sms.c
Fix rilmodem tests failures when built in ci-train
> Fix rilmodem tests

- drivers/mtk2modem/gprs.c
- drivers/mtkmodem/gprs.c
- drivers/mtkmodem/radio-settings.c
- drivers/qcommsimmodem/gprs.c
- drivers/qcommsimmodem/radio-settings.c
- drivers/rilmodem/gprs.c
- drivers/rilmodem/gprs.h
- drivers/rilmodem/radio-settings.c
- drivers/rilmodem/radio-settings.h
- gril/grilreply.c
- include/gprs.h
- plugins/ril.c
- src/gprs.c
Enable switching slot capabilities in multi-SIM modems.
> Switch slot capabilities

- drivers/rilmodem/network-registration.c
- gril/grilreply.c
> Fix name parsing for turbo

- Makefile.am
- configure.ac
- plugins/android-wakelock.c
Remove --enable-android-wakelock and build android-wakelock plugin whenever rilmodem is built.
> Remove --enable-android-wakelock option

- .gitignore
- Makefile.am
- drivers/rilmodem/devinfo.c
- drivers/rilmodem/rilutil.c
- drivers/rilmodem/rilutil.h
- unit/rilmodem-test-engine.c
- unit/rilmodem-test-engine.h
- unit/test-rilmodem-cv.c
- unit/test-rilmodem-devinfo.c
- unit/test-rilmodem-gprs.c
Rilmodem GPRS tests. The PR includes a rewrite of our testing framework.
> Rilmodem GPRS tests

- .gitignore
- Makefile.am
- drivers/rilmodem/gprs-context.c
- gril/gril.c
- unit/rilmodem-test-engine.h
- unit/test-rilmodem-cv.c
- unit/test-rilmodem-gprs-context.c
- unit/test-rilmodem-gprs.c
New gprs-context tests that use the rilmodem test engine.
> gprs-context rilmodem tests

- drivers/rilmodem/sim.c
RIL_REQUEST_SET_UICC_SUBSCRIPTION is 115 in RIL version 9 (or earlier)
and 122 in RIL version 10 and later. Since we don't know in advance which
RIL version we are dealing with, we need to make the decision at runtime.
> rilmodem: make SET_UICC_SUBSCRIPTION works on newer devices
