rilmodem/ofono

drivers/mtkmodem/voicecall.c
When an incoming call was being answered immediately after it appearead, RIL_REQUEST_ANSWER was sent and the reply indicated success, but the call was not actually transitioning to the active state. This is a bug in rild because the modem was responding with error "+CME: 3" to the "ATA" command, but nonetheless there is a also bug in ofono because we are letting the user answer the call before the modem is ready. To avoid this, we do not poll for the calls after sending an MTK_CALL_INDIC_MODE_AVAIL, but wait for the MTK_RIL_UNSOL_CALL_PROGRESS_INFO that indicates that the modem is ready to do so.
=> mtkmodem: Fix failure to answer fast a call

gril/grilrequest.c, unit/test-grilrequest.c
Contexts with empty APNs can be accepted as valid by mobile networks, for instance Movistar Spain. So we should try to setup the data call in that case.
=> Support empty apn

drivers/rilmodem/gprs-context.c
Set auth type to use either CHAP or PAP when there is a user set in the APN data, or use none if there is no user.
=> rilmodem: Set auth type depending on APN data

plugins/ubuntu-apndb.c
Provision APN entries that do not explicitly set the type or when type="*". In the AOSP code this is equivalent to an APN valid for all types, so we do the same here. See
https://bugs.launchpad.net/ubuntu/+source/ofono/+bug/1437200
=> Provision APNs without explicit type

include/modem.h, plugins/mtk.c, src/gprs.c, src/modem.c
This changes forces settings so only one slot can have ConnectionManager.Powered set at a time, for multi-sim dual-standby devices.
=> Force only one slot with ConnectionManager.Powered set

doc/connman-api.txt, src/gprs.c
Add Preferred property to org.ofono.ConnectionContext. This property is a way to express that a context is preferred over the others for activation. It is a facility used by the ofono clients, but it is not actually used internally.
See
https://bugs.launchpad.net/ubuntu/+source/ofono/+bug/1361864
for more information.
=> Add Preferred property to contexts

drivers/rilmodem/gprs-context.c
If an unsolicited DATA_CALL_LIST is received with
no calls, and the rilmodem gprs-context has an active
call, notify ofono core that it has disconnected.
This is a partial fix for the following two bugs:
https://bugs.launchpad.net/ubuntu-rtm/+source/ofono/+bug/1436427
https://bugs.launchpad.net/canonical-devices-system-image/+bug/1436411
=> rilmodem: if data call list is empty, disconnect

drivers/rilmodem/sim.c, gril/grilreply.c, gril/grilreply.h, gril/grilrequest.c, gril/grilrequest.h, unit/test-grilreply.c, unit/test-grilrequest.c
Use AT+EPINC command to get available retries for PIN, PIN2, PUK, and PUK2 for MTK modems. This way we can know the available retries even when we have not tried to enter any password yet. This PR fixes
https://bugs.launchpad.net/ubuntu/+source/indicator-network/+bug/1436820/
=> Make PIN retries always available for MTK modems

plugins/ubuntu-apndb.c
Sets IPv4 instead of IPv6 as the protocol when the last one is the value in the provisioning database.
=> ubuntu-apndb: Ignore IPv6 protocol attribute

doc/connman-api.txt, src/gprs.c, test/reset-contexts
Add ResetContexts method to org.ofono.ConnectionManager interface. This method removes all current contexts and runs re-provisioning. Fix for
https://bugs.launchpad.net/ubuntu/+source/ofono/+bug/1338758
=> Reset contexts

test/list-modems
This change adds a new default behavior to list-modems; any
Modem or other interface properties that could be somehow
tied to a user ( Serial, SubscriberIdentity, SubscriberNumbers,
... ) are now displayed obfuscated instead of cleartext.  The
cmd-line args -p or --private must be specified to dump the
actual contents of these properties.
https://bugs.launchpad.net/canonical-devices-system-image/+bug/1438715
=> test: add privacy support to list-modems (-p)

test/set-context-property
This pull-request fixes the multi-SIM behavior of the test script set-context-property.  It also adds support for the new 'Preferred' property, which needs to be built a dbus.Boolean wrapped in a variant.
This fixes the following bugs:
* https://bugs.launchpad.net/ubuntu/+source/ofono/+bug/1454751
* https://bugs.launchpad.net/ubuntu/+source/ofono/+bug/1454756
=> Fix set ctx prop

test/rilmodem/sim/simtestutil.py, test/rilmodem/sim/test-no-sims-offline, test/rilmodem/sim/test-sims-offline
Fix SIM test scripts when run on arale.  Fix for:
https://bugs.launchpad.net/ubuntu-rtm/+source/ofono/+bug/1457775
=> test/rilmodem/sim: fix scripts on arale

test/list-modems
This change inverts the initial implementation of the
privacy flag no longer making it the default behavior.
The original change broke autopkg tests for python-dbusmock,
and also was probably not acceptable to upstream as it
changed the default behavior of the script.
=> test: reverse meaning of list-modems -p

Makefile.am, drivers/qcommsimmodem/qcom_msim_modem.c, drivers/qcommsimmodem/qcom_msim_modem.h, drivers/qcommsimmodem/radio-settings.c, drivers/rilmodem/radio-settings.c, drivers/rilmodem/radio-settings.h, include/radio-settings.h, plugins/ril.c, src/radio-settings.c
This is improvement of qcom-msim plugin that allow you to use other SIM slot and be able to select which SIM will prefer 3G. This modem has limitation that only 1 SIM can prefer 3G at a time, so the new radio-settings driver will make sure that other SIMs prefer 2G before setting a SIM to prefer 3G. I code this to support more than 2 SIM slots, but there are some constants which assume that only 2 SIM slots are available. If, in the future, there are phones with more than 2 SIM slots, these constants can be edited to support them.
=> Make qcom-msim plugin able to use other SIM slot than first SIM slot.

drivers/mtkmodem/mtkutil.h, drivers/rilmodem/gprs-context.c, drivers/rilmodem/rilutil.h, plugins/mtk.c, plugins/ril.c
Retry when a context deactivation request has finished with an error. We can have these error temporarily for some modems. Solves
https://bugs.launchpad.net/tangxi/+bug/1467191
=> Retry when a context deactivation request has finished with an error

Makefile.am, configure.ac, include/dns-client.h, plugins/c-ares-dns-client.c, src/dns-client.c, src/gprs.c
Resolve, in case the hostname is provided instead of the IP address, MMS proxy / MMSC name using the DNS servers provided by the context. We need the IP so we can set-up a route for them. Also, use the MMSC for the route in case we do not have a MMS proxy. Finally, export proxy
and proxy port as part of the Settings property array, for both combined and mms context types. Client must use these values to connect to make sure the used IP is the same one as the one for the route, as the MMSC might be a balanced server with multiple IPs.
The PR adds an asynchronous DNS client based on c-ares to avoid blocking ofono while doing the DNS lookup. The client integrates with glib's main loop and has a configurable time-out.
=> gprs: Resolve MMS proxy/MMSC host name

src/message-waiting.c
This is a fix for
https://bugs.launchpad.net/canonical-devices-system-image/+bug/1469266
This change has already been submitted and accepted upstream.
=> Fix writing EF_MWIS SIM file

plugins/c-ares-dns-client.c, src/gprs.c
Disable reverse package filter so we do not need to manipulate the routing table to be able to do DNS lookups using a radio interface.
=> Disable rp for dns lookups

plugins/ril.c
Fix for LP #1490991:
https://bugs.launchpad.net/canonical-devices-system-image/+bug/1490991
=> Do not assert when the radio is unavailable

plugins/ril.c
Revert this commit to land 1.16 first.
This reverts commit e5242a80c878452fec83d654cbf410aeb93f48cd.
=> Revert "ril: Do not assert when the radio is unavailable"

unit/test-grilrequest.c
Latest version of glib test framework complains if you have the same test path for more than test.
=> Avoid duplicate test paths

drivers/rilmodem/phonebook.c
The case of empty EFpbr records was not being considered. Fixes
https://bugs.launchpad.net/ubuntu/+source/ofono/+bug/1492388
=> rilmodem: Fix crash when importing SIM phonebook

plugins/push-notification.c, src/sms.c, src/smsutil.c
Some operators do not set properly the origin port in the SMS header when sending a push notification, so we check only the destination port. Fixes
https://bugs.launchpad.net/ubuntu/+source/nuntium/+bug/1490673
=> Ignore SMS origin port

doc/handsfree-audio-api.txt, include/emulator.h, include/handsfree-audio.h, plugins/hfp_ag_bluez5.c, plugins/hfp_hf_bluez5.c, src/emulator.c, src/handsfree-audio.c
Until now the BlueZ 5 plugin for HFP AG support didn't registered a handsfree audio card which is necessary to get others (PulseAudio) be notified that we're connected with a HFP HF device. In former times with BlueZ 4 this wasn't necessary as the profile management was done differently. Nowadays with BlueZ 5 ofono has the main control over the HFP profile connection endpoint and we have to share a SCO connection with the actual user (PulseAudio) through the org.ofono.HandsfreeAudio management interface.
PulseAudio will register a org.ofono.HandsfreeAudioAgent with us to get notified when a connection is setup and will call org.ofono.HandsfreeAudioCard.Connect when needed.
=> Improve HFP AG support for BlueZ 5.x

gril/gril.c, gril/grilreply.c
Address FIXME comments, by either using the malformed variable in the
ril parcel structure or by removing them if appropriate.
=> gril: Address FIXME comments

Makefile.am, configure.ac, plugins/upower.c
This new plugin adds support for the HFP battery indicator when running with Bluez5.  It reads battery events from the upower system daemon, and relays them to any HFP emulator instances associated with the modem.  The plugin currently only supports a single SIM, and as such picks the first modem with available voicecall support ( same as the hfp_ag_bluez5 plugin ).
To test, you need to use a device that includes Bluez5 kernel support ( eg. mako ), and follow the instructions for Bluez5 testing per:
https://wiki.ubuntu.com/Bluetooth/TouchBluez5Testing
=> upower: add bluez5 HFP battery indicator support

include/emulator.h, plugins/hfp_ag_bluez5.c, src/emulator.c
Starting with HFP 1.6 we need to negate with the remote side on the codec we're using first before setting up the SCO channel. This adds support for this.
=> Add support for HFP codec negotiation

Makefile.am, unit/test-rilmodem-cs.c
New style build-time tests ( not really *unit* ) which test the rilmodem call-settings atom.
A dummy socket is constructed, and a ril client instantiated.  The ril client connect to the dummy socket, which will block on reading the RIL request, and then send back an expected RIL reply.  The request parcel is verified, and the expected return values are checked in the final callback.
There are some style warning produced by checkpatch that I ignored.  A couple about line lengths, as these are re-impls of core functions, I left them as is.  The only warnings I couldn't make go away were those about the new (*StartFunc) typedef.
=> Add rilmodem cs unit tests

src/voicecall.c
When the voicecall atom is unregistered we remove all HFP support as
well but were supplying a zero as value to the emulator status
callbacks which caused the process to crash as we were dereferencing
the supplied value always and not respecting a zero as indicator to
reset.
=> voicecall: don't dereference a supplied null value

.gitignore, Makefile.am, drivers/rilmodem/sms.c, unit/rilmodem-test-server.c, unit/rilmodem-test-server.h, unit/test-rilmodem-cs.c, unit/test-rilmodem-sms.c
This change adds new SMS unit tests.  Note, this change required re-factoring rilmodem-test-server, which includes adding support for testing incoming RIL unsolicited replies.
All except the last two commits have been merged upstream.  The last two commits have been submitted, but not yet accepted.
=> New rilmodem sms tests

plugins/ril.c
The gril vendor, which can be changed by derived plugins, was incorrently
always set as AOSP.
=> ril: Set properly gril vendor

unit/test-grilreply.c
The reply parsing logic for a SET_FACILITY_LOCK was
re-factored based on upstream changes. One change
made is that the retries return value is now set to
0 for a reply with no data, like done by mako.  This
used to cause a -1 to be returned.  The change ensures
that the 0 is logged if no data is present, and -1
logged if returned by rild.
Note - the caller of the reply parse function discards
the retries return value, so this change is basically
a no-op functionally.
=> unit: fix test-grilreply set_facility_lock test

Makefile.am, configure.ac, include/wakelock.h, plugins/android-wakelock.c, src/main.c, src/ofono.h, src/voicecall.c, src/wakelock.c
It turned out that when a HFP HF device sends the voice dial command we don't have always enough time until the system goes to sleep again after we did the first steps of processing as we have some kind of different IO things involved in that process. Therefore we acquire the global system wakelock first before doing any further IO to ensure the system stays awake a bit longer until all necessary steps are performed to setup the voicecall where some will acquire additional wakelocks a soon as we have IO activity or created a proper call object on dbus.
=> Implement wakelock support

drivers/qcommsimmodem/radio-settings.c
Normally, to set a slot as 3G when there are 2 SIMs in the device, radio settings must set other slot to 2G first. But if the other slot is empty, this action will fail. This PR make sure that radio settings will skip the empty slot. Along the way, I've refactored code around so that the code is cleaner.
=> qcommsimmodem: Fix setting 3G preference when one of the slot is empty.

Makefile.am, configure.ac, include/log.h, include/system-settings.h, plugins/accounts-settings.c, src/emulator.c, src/system-settings.c
Adds a generic interface to access system settings, and a concrete implementation that uses AccountsService settings.
This PR is needed to be able to access the preferred modem for voice calls, which in turn is needed to handle outgoing calls started from a HFP headset.
=> Support for system settings

drivers/rilmodem/sim.c
During modem powering up, __GET_SIM_STATUS__ might fail with error _RADIO_NOT_AVAILABLE_, so check it before parsing.
=> rilmodem: check parcel error for GET_SIM_STATUS reply first

plugins/qcom-msim.c, plugins/ril.c, plugins/rildev.c
Two things addressed in this pull request. One commit for each.
This first thing is ril daemon socket path for the 2nd instance should be _/dev/socket/rild2_ instead of _/dev/socket/rild1_. See https://android.googlesource.com/platform/hardware/ril/+/android-5.0.0_r1/libril/ril.cpp#59
The other thing is some rild implementation issues radio state change event with state __UNAVAILABLE__ after __RIL_CONNECTED__. After that, rild is expecting a reset by __RADIO_POWER__ request to __OFF__. This is actually etched in Android telephony framework and for aforementioned ril implementations, they simply cannot transit its internal state to on without such reset. See https://android.googlesource.com/platform/frameworks/opt/telephony/+/android-5.1.1_r1/src/java/com/android/internal/telephony/RIL.java …
=> fix misaligned dual sim behavior compared to AOSP

unit/test-grilreply.c
unit/test-grilreply.c: In function 'test_reply_call_fail_cause_valid':
unit/test-grilreply.c:1689:2: error: comparison of unsigned expression >= 0 is always true [-Werror=type-limits]
cc1: all warnings being treated as errors
Makefile:3667: recipe for target 'unit/test-grilreply.o' failed
make[1]: *** [unit/test-grilreply.o] Error 1
make[1]: *** Waiting for unfinished jobs....
Makefile:2030: recipe for target 'all' failed
make: *** [all] Error 2
=> build: fix -Werror=type-limits

drivers/rilmodem/gprs.c, src/gprs.c
In some cases it is possible that a context is opened after a detach event has been received, and right before an attach, depending on the modem. We can sure that those contexts are removed to keep consistency. Fixes LP: #1533508.
=> Fix for lp1533508

drivers/rilmodem/gprs.c, drivers/rilmodem/radio-settings.c, plugins/ril.c
Create radio settings atom in pre-sim state so we can set FastDormancy and enter low power state even when there is no SIM.
=> ril: allow entering low power state with no SIM

src/voicecall.c
- China telecom regulation required to have 110,119,120,122 as emergency call number.
- In 3GPP TS 51.010-1 (GSM) and 3GPP 34.123-1 (WCDMA) Section 13.2.1
The following emergency numbers shall be stored in the UE for use without USIM:
000, 08, 112, 110, 118, 119, 911 and 999.
- In 3GPP TS 51.010-1 (GSM) Section 26.9.6
When no emergency numbers are stored within the SIM/USIM the following numbers shall
be stored in the ME for use as emergency numbers: 112, and 911.
- Tested on China Mobile USIM Card, it has 4 records of emergency numbers, but all
empty string. It shall use the default non-SIM numbers.
- Tested two other operators in Taipei (CHT and TWN), both have empty record.
=> voicecall: add emergency numbers required for China Market.

drivers/rilmodem/radio-settings.c
Moved an error log that landed in the wrong function,
and also re-worked some code to check NULL before a
the local variable is used.
=> rilmodem: radio-settings: cleanup last merge

plugins/qcom-msim.c, plugins/rildev.c
Create modems only when the unix socket used to communicate with rild exists. This is checked dynamically by using inotify.
=> Check socket path

plugins/qcom-msim.c
Although I've added a few custom request for qcom-msim there is no
request-ID-to-string function for these request. As a result, there is
no request name in the log when OFONO_RIL_TRACE is enabled. This commit
add that function so that the log will be more complete.
=> plugins: add request-ID-to-string function for qcom-msim

gril/grilreply.c
QCOM's sim status reply contains 4 more elements in the struct:
remaining_count_{pin,puk}1 and remaining_count_{pin,puk}2. We have to
read that from the parcel.
=> gril: fix struct size mismatch for QCOM's sim status

drivers/rilmodem/voicecall.c
Previously, the oFono's dial callback will be kept in vd
(ril_voicecall_data) when the RIL's DIAL request is responded, which
will be called later when GET_CURRENT_CALL's callback find out what is
the new call's id.
The problem is that a UNSOL_RESPONSE_CALL_STATE_CHANGED might be
issued before the DIAL request is responded, resulting in a
GET_CURRENT_CALL request being sent before the callback being put in
vd. When we get the result, the callback will notice the new call but
will not notice about the pending dial request from oFono, and the
following GET_CURRENT_CALL request will not notice the new call anymore.
Now, the pending oFono's dial callback will never be called, and the
DBus call will timeout.
This commit make our dial function keeps the oFono's dial callback
right after the …
=> rilmodem: fix race condition in voice call dialling
